### Site Settings ###
title               : Dunc Graham
description         : >-
                      I'm a game designer with experience
                      ranging from escape rooms to digital games.
baseurl             : ""                                # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : duncathan/duncathan.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
# remote_theme        : YoussefRaafatNasry/portfolYOU@v2.3.0
domain              : duncathan.com
url                 : "https://duncathan.com"


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Dunc Graham
  pronouns          : hii/him
  image             : https://duncathan.com/assets/dunc.jpg
  email             : dunc@duncathan.com
  twitter           : duncathan_salt
  github            : duncathan
# behance           : your_username
# dribbble          : your_username
# facebook          : your_username
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
# linkedin          : your_username
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /:categories/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /:collection/:name


### Analytics ###
# analytics:
#   enabled: false                                        # Set true to enable analytics
#   google:
#     tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:                                              # For Documentation Only
      path: ""                                          # For Documentation Only
      type: "elements"                                  # For Documentation Only
    values:                                             # For Documentation Only
      layout: "element"                                 # For Documentation Only
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
